title: Mostafa Abdelrashid
logo: assets/img/WhatsApp Image 2024-06-27 at 12.25.44_df314a39.jpg
 image_size: "120x120" 
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
